# install.packages(c("tidyverse", "purrr", "readr", "readxl", "openxlsx", "writexl", "yfR", "ISIN", "rvest", "tidyquant", "nloptr", "arrow"))
# install.packages("BLCOP")
# install.packages("PerformanceAnalytics")
library(yfR)
library(tidyverse)
library(purrr)
library(readr)
library(readxl)
library(openxlsx)
library(writexl)
# library(ISIN)
library(rvest)
library(tidyquant)
library(quantmod)
# library(targets)
library(nloptr)
library(quadprog)
library(arrow)
library(BLCOP)
