# install.packages(c("tidyverse", "purrr", "readr", "readxl", "openxlsx", "writexl", "yfFR", "ISIN", "rvest", "tidyquant", "nloptr"))
library(yfR)
library(tidyverse)
library(purrr)
library(readr)
library(readxl)
library(openxlsx)
library(writexl)
# library(ISIN)
library(rvest)
library(tidyquant)
library(quantmod)
# library(targets)
library(nloptr)
library(quadprog)
library(arrow)
